
const CFG={tile:34,still:5,grav:2350,p:{acc:1850,max:520,jump:690,dash:780,dc:.45,sw:.16},ups:{speed:{n:"Speed",c:2,m:8,a:42},jump:{n:"Jump",c:2,m:8,a:32},dash:{n:"Dash",c:2,m:8,a:45}},levels:[
{id:"1-1",name:"Clutter Hallway",reward:2,map:["################################","#P....#......B.....#.........G#","#.##..#.#########..#.####.#####","#..#..#.....C......#....#.....#","##.#.#####.#####.######.#####.#","#..#.....#.....#......#.....#.#","#.#####.#####.###.##.#####.#..#","#.....#.....#.....#L#.....#...#","#####.###.#.#######.#####.###.#","#.....#...#.....B.......#.....#","#.#####.#######.#####.#.#####.#","#.....#.....C...#...#.#.....#.#","#.###.#####.#####.#.#.#####.#.#","#...#.......#.....#.....N...#.#","#X#X#XXXXXXX#XXXXX#XXXXX#XXX#.#","################################"]},
{id:"1-2",name:"Maze of Bad Decisions",reward:2,map:["####################################","#P.....#.......#......B....#.....G#","#####.#.#####.#.##########.#.######","#.....#.....#.#....C.......#......#","#.#########.#.###############.##..#","#.....B.....#.......#.........#...#","###.###########.###.#.#########.###","#...#.....L.....#...#.....C.....#.#","#.###.###########.###########.###.#","#.....#.........#.....B.....#.....#","#####.#.#######.###########.#####.#","#...#.#.....N...#.....#.....#.....#","#.#.#.###########.###.#.#####.###.#","#.#.......B.......#...#.......#...#","#.#################.###########.#X#","#.............C.................#X#","####################################"]},
{id:"1-3",name:"Cannon Clutter Factory",reward:2,map:["########################################","#P....#.......#.......#.......#.......G#","#.##.###.###.#.#####.#.#####.#.########","#..#.....#...#...C...#...B...#........#","##.#######.#####.###########.########.#","#..B......#.....#.....L.....#......#..#","#.#########.###.###########.####.#.#.##","#.....C.....#...#.....N.....#....#.#..#","#####.#######.###.###########.####.##.#","#.....#.....#.....#.....B.....#.......#","#.###.#.###.#######.###########.#####.#","#...#.#...#.....C...#.........#.....#.#","###.#.###.###########.###.###.#####.#.#","#...#.....#.....B.....#...#.........#.#","#.#########.###########.#############.#","#......N..........L........C..........#","#XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.#","########################################"]}]};
const T=[[".","Empty","empty",""],["#","Solid","solid","#"],["P","Player","player","P"],["G","Goal","goal","G"],["B","Touch Boost","boost","B"],["C","Chaser","chaser","C"],["L","Laser","laser","L"],["N","Cannon","cannon","N"],["X","Breakable","breakable","X"],["^","Spike","spike","^"]];
const $=id=>document.getElementById(id),S=["start","diff","rick","menu","levels","custom","ups","settings","editor","game"];
const cvs=$("c"),ctx=cvs.getContext("2d"),SK="es_v3_save",CK="es_v3_custom";
let save=load(SK,{points:0,beaten:{},bests:{},ups:{speed:0,jump:0,dash:0},set:{shake:1,sound:1,fx:1,brake:1,death:1}});
let customs=load(CK,[]),keys={},touch={left:0,right:0,jump:0,dash:0},g=null,raf=null,last=0,run=0,ed=[],sel="#",paint=0,audio=null,plist=[],tr=0,aReady=0;
function load(k,f){try{return JSON.parse(localStorage.getItem(k))||f}catch{return f}}function store(){localStorage.setItem(SK,JSON.stringify(save));localStorage.setItem(CK,JSON.stringify(customs))}
function go(id){S.forEach(x=>$(x).classList.remove("active"));$(id).classList.add("active");if(id!="game")stop();ui()}
function stop(){run=0;if(raf)cancelAnimationFrame(raf);raf=null}
function rick(n){$("rickTitle").textContent=n+" was a trap";go("rick")}
function wipe(){if(confirm("Wipe save?")){save={points:0,beaten:{},bests:{},ups:{speed:0,jump:0,dash:0},set:{shake:1,sound:1,fx:1,brake:1,death:1}};store();ui()}}
function ui(){points.textContent=save.points;upPoints.textContent=save.points;["Shake","Sound","Fx","Break","Death"].forEach(n=>{$("set"+n).checked=!!save.set[n.toLowerCase().replace("break","brake")]});levels();customList();ups()}
function levels(){levelList.innerHTML="";CFG.levels.forEach(l=>levelList.appendChild(row(l)))}
function customList(){customList.innerHTML="";if(!customs.length){customList.innerHTML='<p class="muted">No custom levels yet.</p>';return}customs.forEach((l,i)=>{let r=row(l),b=document.createElement("button");b.className="inv";b.textContent="Delete";b.onclick=()=>{if(confirm("Delete custom?")){customs.splice(i,1);store();ui()}};r.appendChild(b);customList.appendChild(r)})}
function row(l){let d=document.createElement("div");d.className="item";let best=save.bests[l.id]?save.bests[l.id].toFixed(2)+"s":"--";d.innerHTML=`<div><b>${esc(l.name)}</b><p>Reward: ${l.reward||2} points • Best: ${best}</p></div><button>Play</button>`;d.querySelector("button").onclick=()=>start(l);return d}
function ups(){upList.innerHTML="";for(let k in CFG.ups){let u=CFG.ups[k],lv=save.ups[k]||0,m=lv>=u.m,d=document.createElement("div");d.className="item";d.innerHTML=`<div><b>${u.n} Lv ${lv}/${u.m}</b><p>Cost: ${m?"MAX":u.c+" points"}</p></div><button ${m?"disabled":""}>Upgrade</button>`;d.querySelector("button").onclick=()=>{if(save.points>=u.c&&!m){save.points-=u.c;save.ups[k]++;store();ui()}};upList.appendChild(d)}}
["Shake","Sound","Fx","Break","Death"].forEach(n=>{$("set"+n).onchange=e=>{let k=n.toLowerCase().replace("break","brake");save.set[k]=e.target.checked?1:0;store();if(k=="sound"&&!save.set.sound)musicStop();if(k=="sound"&&save.set.sound)musicStart()}})
function stat(){return{acc:CFG.p.acc+save.ups.speed*100,max:CFG.p.max+save.ups.speed*CFG.ups.speed.a,jump:CFG.p.jump+save.ups.jump*CFG.ups.jump.a,dash:CFG.p.dash+save.ups.dash*CFG.ups.dash.a}}
function newGrid(w,h,maze){ed=[];for(let y=0;y<h;y++){let r=[];for(let x=0;x<w;x++){let b=y==0||x==0||y==h-1||x==w-1;r.push(b?"#":".")}ed.push(r)}if(maze)for(let y=2;y<h-2;y+=2)for(let x=2;x<w-2;x+=4){ed[y][x]="#";if(x+1<w-1)ed[y][x+1]="#"}ed[1][1]="P";ed[h-2][w-2]="G";if(maze){ed[3]?.splice(5,1,"B");ed[4]?.splice(9,1,"C");ed[6]?.splice(14,1,"L");ed[8]?.splice(20,1,"N")}renderEd();syncText()}
function pal(){palette.innerHTML="";T.forEach(t=>{let b=document.createElement("button");b.className="tileBtn"+(sel==t[0]?" on":"");b.innerHTML=`<span class="sw ${t[2]}">${t[3]}</span><span>${t[1]}</span>`;b.onclick=()=>{sel=t[0];selName.textContent=t[1];pal()};palette.appendChild(b)})}
function renderEd(){edGrid.innerHTML="";edGrid.style.gridTemplateColumns=`repeat(${ed[0].length},28px)`;sizeText.textContent=ed[0].length+" × "+ed.length;for(let y=0;y<ed.length;y++)for(let x=0;x<ed[0].length;x++){let ch=ed[y][x],t=T.find(v=>v[0]==ch)||T[0],c=document.createElement("div");c.className="cell "+t[2];c.textContent=t[3];c.onpointerdown=e=>{e.preventDefault();paint=1;pc(x,y)};c.onpointerenter=()=>{if(paint)pc(x,y)};edGrid.appendChild(c)}}
onpointerup=()=>paint=0;function pc(x,y){if(sel=="P"||sel=="G")ed.forEach(r=>r.forEach((v,i)=>{if(v==sel)r[i]="."}));ed[y][x]=sel;renderEd();syncText()}function syncText(){mapText.value=ed.map(r=>r.join("")).join("\n")}
function textToGrid(){let lines=mapText.value.split("\n").filter(Boolean),w=Math.max(12,...lines.map(l=>l.length));ed=lines.map(l=>Array.from({length:w},(_,i)=>T.some(t=>t[0]==(l[i]||"."))?l[i]||".":"."));renderEd();syncText()}
function edLevel(){syncText();let map=ed.map(r=>r.join("")),j=map.join("");if(!j.includes("P")||!j.includes("G"))return alert("Needs P and G"),null;return{id:"custom-"+Date.now(),name:edName.value.trim()||"Custom Level",reward:2,custom:1,map}}
function saveCustom(){let l=edLevel();if(l){customs.push(l);store();ui();alert("Saved!")}}function exportCustom(){let l=edLevel();if(l)share.value=btoa(unescape(encodeURIComponent(JSON.stringify(l))))}function importCustom(){try{let l=JSON.parse(decodeURIComponent(escape(atob(share.value.trim()))));if(!Array.isArray(l.map))throw 0;customs.push({...l,id:"custom-"+Date.now(),custom:1});store();ui();alert("Imported!")}catch{alert("Import failed")}}
function start(l){size();go("game");musicStart();g={level:l,tiles:[],boosts:[],en:[],pro:[],pt:[],wind:[],cam:{x:0,y:0},shake:0,t:0,idle:CFG.still,dead:0,done:0,msg:"",blink:R(1,3),exp:".",expT:0,st:stat(),p:{x:60,y:60,w:24,h:32,vx:0,vy:0,on:0,face:1,dc:0,sw:0,jh:0}};parse(l.map);hudName.textContent=l.name;hudBest.textContent=save.bests[l.id]?save.bests[l.id].toFixed(2)+"s":"--";run=1;last=performance.now();raf=requestAnimationFrame(loop)}
function parse(map){map.forEach((r,y)=>[...r].forEach((ch,x)=>{let X=x*CFG.tile,Y=y*CFG.tile;if(ch=="#"||ch=="X"||ch=="^")g.tiles.push({x:X,y:Y,w:CFG.tile,h:CFG.tile,type:ch});if(ch=="B")g.boosts.push({x:X+5,y:Y+5,w:24,h:24,used:0});if(ch=="P"){g.p.x=X+5;g.p.y=Y}if(ch=="G")g.goal={x:X,y:Y,w:CFG.tile,h:CFG.tile};if("CLN".includes(ch))g.en.push({kind:ch,x:X+4,y:Y+2,w:26,h:32,vx:0,vy:0,hp:ch=="N"?3:2,cd:R(.4,1.3),on:0})}))}
function loop(now){if(!run||!g)return;let dt=Math.min((now-last)/1000,1/30);last=now;upd(dt);draw();raf=requestAnimationFrame(loop)}
function upd(dt){let p=g.p,ix=(keys.KeyD||keys.ArrowRight||touch.right?1:0)-(keys.KeyA||keys.ArrowLeft||touch.left?1:0),jp=!!(keys.KeyW||keys.ArrowUp||keys.Space||touch.jump),ds=!!(keys.KeyQ||keys.ShiftLeft||touch.dash);if(!g.dead&&!g.done){g.t+=dt;if(ix){p.vx+=ix*g.st.acc*dt;p.vx=cl(p.vx,-g.st.max,g.st.max);p.face=ix;g.idle=CFG.still}else if(Math.abs(p.vx)<25&&p.on)g.idle-=dt;else g.idle=Math.max(0,g.idle-dt*.15);if(jp&&!p.jh&&p.on){p.vy=-g.st.jump;p.on=0;g.idle=CFG.still;fx(p.x+12,p.y+32,12)}p.jh=jp;if(ds&&p.dc<=0){p.vx=p.face*g.st.dash;p.dc=CFG.p.dc;expr(p.face>0?">":"<",.18);shake(5);fx(p.x+12,p.y+16,25)}if(keys.MouseDown&&p.sw<=0)swing();if(g.idle<=0)die("You stopped moving.")}p.dc-=dt;p.sw-=dt;g.blink-=dt;g.expT-=dt;if(g.expT<=0)g.exp=".";if(g.blink<=0&&!g.dead&&!g.done){expr("-",.12);g.blink=R(1.5,4)}p.vy+=CFG.grav*dt;p.vx*=p.on?.84:.97;move(p,p.vx*dt,0);move(p,0,p.vy*dt);g.boosts.forEach(b=>{if(!b.used&&hit(p,b)){b.used=1;p.vy=-850;expr("O",.25);g.idle=CFG.still;fx(b.x+12,b.y+12,35);shake(7);beep(740,.08)}});en(dt);proj(dt);parts(dt);wind(dt);if(!g.dead&&g.goal&&hit(p,g.goal))done();g.cam.x=cl(p.x-cvs.width/2,0,Math.max(0,lw()-cvs.width));g.cam.y=cl(p.y-cvs.height/2,0,Math.max(0,lh()-cvs.height));if(g.shake>0)g.shake-=dt*24;hudTime.textContent=g.t.toFixed(2);hudIdle.textContent=Math.max(0,g.idle).toFixed(1)}
function en(dt){let p=g.p;g.en.forEach(e=>{if(e.dead)return;if(e.kind=="C"){let d=Math.sign(p.x-e.x)||1;e.vx+=d*520*dt;e.vx=cl(e.vx,-210,210)}if(e.kind=="L"){e.cd-=dt;if(e.cd<=0&&Math.abs(p.y-e.y)<90){let d=Math.sign(p.x-e.x)||1;g.pro.push({kind:"laser",x:e.x+13,y:e.y+12,w:28,h:6,vx:d*620,vy:0,life:1.8});e.cd=1.1;fx(e.x+13,e.y+16,8)}}if(e.kind=="N"){e.cd-=dt;if(e.cd<=0){let d=Math.sign(p.x-e.x)||1;g.pro.push({kind:"cannon",x:e.x+13,y:e.y+10,w:16,h:16,vx:d*360,vy:-120,life:2.7});e.cd=1.6;shake(3)}}e.vy+=CFG.grav*dt;e.vx*=e.on?.88:.98;move(e,e.vx*dt,0);move(e,0,e.vy*dt);if(!g.dead&&hit(p,e)){expr("O",.12);die("Enemy bonk.")}})}
function proj(dt){let p=g.p;g.pro.forEach(pr=>{pr.x+=pr.vx*dt;pr.y+=pr.vy*dt;if(pr.kind=="cannon")pr.vy+=500*dt;pr.life-=dt;if(!g.dead&&hit(p,pr))die(pr.kind=="laser"?"Lasered.":"Cannoned.");if(pr.kind=="cannon")for(let i=g.tiles.length-1;i>=0;i--){let t=g.tiles[i];if(t.type=="X"&&hit(pr,t)){g.tiles.splice(i,1);pr.life=0;fx(t.x+17,t.y+17,30);if(save.set.brake)shake(8)}}});g.pro=g.pro.filter(p=>p.life>0)}
function move(o,dx,dy){o.x+=dx;o.y+=dy;if(dy)o.on=0;for(let t of g.tiles){if(!hit(o,t))continue;if(t.type=="^"&&o==g.p){die("Spiked.");continue}if(t.type!="#"&&t.type!="X")continue;if(dx>0){o.x=t.x-o.w;o.vx=0}if(dx<0){o.x=t.x+t.w;o.vx=0}if(dy>0){o.y=t.y-o.h;o.vy=0;o.on=1}if(dy<0){o.y=t.y+t.h;o.vy=0}}}
function swing(){let p=g.p;p.sw=CFG.p.sw;g.idle=CFG.still;let h={x:p.face>0?p.x+p.w:p.x-48,y:p.y+4,w:48,h:28};fx(h.x+24,h.y+14,10);beep(320,.04);g.en.forEach(e=>{if(!e.dead&&hit(h,e)){e.hp--;e.vx+=p.face*330;expr("O",.15);fx(e.x+13,e.y+16,20);if(e.hp<=0)e.dead=1}});for(let i=g.tiles.length-1;i>=0;i--){let t=g.tiles[i];if(t.type=="X"&&hit(h,t)){g.tiles.splice(i,1);fx(t.x+17,t.y+17,25);if(save.set.brake)shake(6)}}}
function done(){g.done=1;expr("^",999);let old=save.bests[g.level.id];if(!old||g.t<old)save.bests[g.level.id]=g.t;if(!save.beaten[g.level.id]){save.beaten[g.level.id]=1;save.points+=g.level.reward||2}store();g.msg="Completed! Press Enter.";fx(g.goal.x+15,g.goal.y+15,70);shake(10);ui()}
function die(m){if(g.dead||g.done)return;g.dead=1;expr("X",999);g.msg=m+" Press R.";fx(g.p.x+12,g.p.y+15,90);if(save.set.death)shake(18);beep(90,.2)}
function expr(e,t){g.exp=e;g.expT=t}function shake(n){if(save.set.shake)g.shake=Math.max(g.shake,n)}function fx(x,y,n){if(!save.set.fx)return;for(let i=0;i<n;i++)g.pt.push({x,y,vx:R(-360,360),vy:R(-360,360),life:R(.25,.8),s:R(2,7)})}function parts(dt){g.pt.forEach(p=>{p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=780*dt;p.life-=dt});g.pt=g.pt.filter(p=>p.life>0)}
function wind(dt){if(!save.set.fx)return;if(Math.random()<12*dt)g.wind.push({x:g.cam.x+cvs.width+20,y:g.cam.y+R(0,cvs.height),vx:R(-900,-500),life:R(.2,.6),len:R(30,90)});g.wind.forEach(w=>{w.x+=w.vx*dt;w.life-=dt});g.wind=g.wind.filter(w=>w.life>0)}
function draw(){let ox=g.shake>0?R(-g.shake,g.shake):0,oy=g.shake>0?R(-g.shake,g.shake):0;ctx.clearRect(0,0,cvs.width,cvs.height);ctx.save();ctx.translate(-g.cam.x+ox,-g.cam.y+oy);bg();tiles();boosts();goal();enDraw();proDraw();player();ptDraw();windDraw();ctx.restore();if(g.dead||g.done){ctx.fillStyle="rgba(0,0,0,.76)";ctx.fillRect(0,cvs.height/2-54,cvs.width,108);ctx.strokeStyle="#fff";ctx.strokeRect(24,cvs.height/2-42,cvs.width-48,84);ctx.fillStyle="#fff";ctx.textAlign="center";ctx.font="bold 30px Arial";ctx.fillText(g.msg,cvs.width/2,cvs.height/2+8);ctx.textAlign="left"}}
function bg(){ctx.fillStyle="#070707";ctx.fillRect(0,0,lw(),lh());ctx.strokeStyle="#181818";ctx.lineWidth=1;for(let x=0;x<lw();x+=CFG.tile)line(x,0,x,lh());for(let y=0;y<lh();y+=CFG.tile)line(0,y,lw(),y)}
function tiles(){g.tiles.forEach(t=>{if(t.type=="#"){ctx.fillStyle="#ddd";ctx.fillRect(t.x,t.y,t.w,t.h);ctx.strokeStyle="#000";ctx.lineWidth=4;ctx.strokeRect(t.x,t.y,t.w,t.h)}else if(t.type=="X"){ctx.fillStyle="#777";ctx.fillRect(t.x,t.y,t.w,t.h);ctx.strokeStyle="#fff";ctx.lineWidth=2;ctx.strokeRect(t.x+5,t.y+5,t.w-10,t.h-10)}else{ctx.fillStyle="#fff";ctx.beginPath();ctx.moveTo(t.x,t.y+t.h);ctx.lineTo(t.x+t.w/2,t.y);ctx.lineTo(t.x+t.w,t.y+t.h);ctx.closePath();ctx.fill()}})}
function boosts(){g.boosts.forEach(b=>{if(b.used)return;ctx.strokeStyle="#fff";ctx.lineWidth=4;ctx.beginPath();ctx.arc(b.x+12,b.y+12,13+Math.sin(performance.now()/90)*2,0,Math.PI*2);ctx.stroke();ctx.fillStyle="#aaa";ctx.beginPath();ctx.arc(b.x+12,b.y+12,7,0,Math.PI*2);ctx.fill()})}
function goal(){let z=g.goal;if(!z)return;ctx.fillStyle="#fff";ctx.fillRect(z.x+10,z.y+5,22,20);ctx.fillStyle="#000";ctx.fillRect(z.x+6,z.y+4,6,z.h)}
function enDraw(){g.en.forEach(e=>{if(e.dead)return;ctx.fillStyle=e.kind=="N"?"#444":"#111";ctx.fillRect(e.x,e.y,e.w,e.h);ctx.strokeStyle="#fff";ctx.lineWidth=3;ctx.strokeRect(e.x,e.y,e.w,e.h);ctx.fillStyle="#fff";ctx.font="bold 15px monospace";ctx.fillText(e.kind,e.x+8,e.y+21)})}
function proDraw(){g.pro.forEach(p=>{ctx.fillStyle="#fff";if(p.kind=="laser")ctx.fillRect(p.x,p.y,p.w,p.h);else{ctx.beginPath();ctx.arc(p.x+8,p.y+8,8,0,Math.PI*2);ctx.fill()}})}
function player(){let p=g.p;if(!g.dead){ctx.fillStyle="#fff";ctx.fillRect(p.x,p.y,p.w,p.h);ctx.strokeStyle="#000";ctx.lineWidth=3;ctx.strokeRect(p.x,p.y,p.w,p.h)}ctx.fillStyle="#000";ctx.font="bold 18px monospace";let eye=g.exp=="."?(p.face>0?">":"<"):g.exp;ctx.fillText(eye,p.x+7,p.y+21);if(p.sw>0){ctx.fillStyle="#fff";let sx=p.face>0?p.x+p.w:p.x-48;ctx.fillRect(sx,p.y+9,48,8);ctx.strokeStyle="#000";ctx.strokeRect(sx,p.y+9,48,8)}}
function ptDraw(){g.pt.forEach(p=>{ctx.fillStyle=p.life>.32?"#fff":"#777";ctx.fillRect(p.x,p.y,p.s,p.s)})}function windDraw(){ctx.strokeStyle="rgba(255,255,255,.55)";ctx.lineWidth=2;g.wind.forEach(w=>line(w.x,w.y,w.x+w.len,w.y))}
function line(a,b,c,d){ctx.beginPath();ctx.moveTo(a,b);ctx.lineTo(c,d);ctx.stroke()}function lw(){return Math.max(...g.level.map.map(r=>r.length))*CFG.tile}function lh(){return g.level.map.length*CFG.tile}function hit(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y}function cl(v,a,b){return Math.max(a,Math.min(b,v))}function R(a,b){return a+Math.random()*(b-a)}function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}function size(){cvs.width=innerWidth;cvs.height=innerHeight}onresize=size;
onkeydown=e=>{keys[e.code]=1;if(game.classList.contains("active")){if(e.code=="KeyR"&&g)start(g.level);if(e.code=="Enter"&&g?.done)go(g.level.custom?"custom":"levels");if(e.code=="Escape")go("menu")}};onkeyup=e=>keys[e.code]=0;cvs.onmousedown=()=>keys.MouseDown=1;onmouseup=()=>keys.MouseDown=0;cvs.ontouchstart=()=>keys.MouseDown=1;cvs.ontouchend=()=>keys.MouseDown=0;function bind(id,k){let b=$(id);b.onpointerdown=e=>{e.preventDefault();touch[k]=1};b.onpointerup=e=>{e.preventDefault();touch[k]=0};b.onpointerleave=()=>touch[k]=0}bind("lt","left");bind("rt","right");bind("jt","jump");bind("dt","dash");
async function musicStart(){if(!save.set.sound)return;if(!aReady){aReady=1;try{let r=await fetch("playlist/playlist.json",{cache:"no-store"});if(r.ok)plist=await r.json()}catch{}if(!Array.isArray(plist)||!plist.length)plist=["playlist/track1.mp3","playlist/track2.mp3","playlist/track3.mp3","playlist/music.mp3","playlist/breakcore.mp3","playlist/song.mp3"]}if(!audio)tryTrack()}
function tryTrack(){if(!save.set.sound||!plist.length||audio)return;let src=plist[tr%plist.length];audio=new Audio(src);audio.volume=.45;audio.onended=()=>{audio=null;tr++;tryTrack()};audio.onerror=()=>{audio=null;tr++;if(tr<plist.length)tryTrack()};audio.play().catch(()=>audio=null)}function musicStop(){if(audio){audio.pause();audio=null}}
function beep(f,d){if(!save.set.sound)return;try{let ac=new (AudioContext||webkitAudioContext)(),o=ac.createOscillator(),gn=ac.createGain();o.frequency.value=f;gn.gain.value=.04;o.connect(gn);gn.connect(ac.destination);o.start();o.stop(ac.currentTime+d)}catch{}}
pal();newGrid(32,16,true);ui();go("start");
