const CONFIG={tile:40,gravity:.75,friction:.82,idle:5,base:{speed:4.2,jump:14,dash:12,swordDamage:1},upgrades:{speed:{name:'Speed',cost:2,max:8,add:.35},jump:{name:'Jump',cost:2,max:8,add:.8},dash:{name:'Dash',cost:2,max:8,add:.75}},levels:[{id:'1-1',name:'Move or Boom',reward:2,map:['########################','#P....................G#','#.............C........#','#......####............#','#......................#','#............####......#','#......................#','########################']},{id:'1-2',name:'The Floor Has Opinions',reward:2,map:['########################','#P....................G#','#....####..............#','#..............C.......#','#.........^^^^.........#','#......####......####..#','#......................#','########################']},{id:'1-3',name:'Breakable Panic',reward:2,map:['########################','#P...........X........G#','#...........XXX........#','#.....C.....XXX........#','#..........#####.......#','#......................#','#...............C......#','########################']}],defaultMap:['########################','#P....................G#','#........C.............#','#......####............#','#...............^^^^...#','#......................#','#......................#','########################'].join('\n')};
const $=id=>document.getElementById(id),screens=['start','diff','rick','menu','levels','upgrades','editor','custom','game'];
const saveKey='move_or_explode_v1_save',customKey='move_or_explode_v1_custom';
let save=load(saveKey,{points:0,beaten:{},upgrades:{speed:0,jump:0,dash:0}}),custom=load(customKey,[]),keys={},mobile={left:false,right:false,jump:false,dash:false},game=null,last=0;
const canvas=$('canvas'),ctx=canvas.getContext('2d');$('edMap').value=CONFIG.defaultMap;
function load(k,d){try{return JSON.parse(localStorage.getItem(k))||d}catch{return d}}function store(){localStorage.setItem(saveKey,JSON.stringify(save))}function storeCustom(){localStorage.setItem(customKey,JSON.stringify(custom))}
function show(id){screens.forEach(s=>$(s).classList.toggle('active',s===id));refresh();if(id==='game')resize()}function rick(n){$('rickTitle').textContent=n+' was a lie';show('rick')}function wipeSave(){if(confirm('Wipe save data?')){save={points:0,beaten:{},upgrades:{speed:0,jump:0,dash:0}};store();refresh()}}
function refresh(){$('pointsA').textContent=save.points;$('pointsB').textContent=save.points;$('pointsC').textContent=save.points;renderLevels();renderUpgrades();renderCustom()}
function stats(){return{speed:CONFIG.base.speed+save.upgrades.speed*CONFIG.upgrades.speed.add,jump:CONFIG.base.jump+save.upgrades.jump*CONFIG.upgrades.jump.add,dash:CONFIG.base.dash+save.upgrades.dash*CONFIG.upgrades.dash.add,swordDamage:1}}
function renderLevels(){let box=$('levelList');box.innerHTML='';CONFIG.levels.forEach(l=>box.appendChild(levelNode(l,false)))}
function renderCustom(){let box=$('customList');box.innerHTML='';if(!custom.length){box.innerHTML='<p class="muted">No custom levels yet. Make one in Level Creator.</p>';return}custom.forEach((l,i)=>{let n=levelNode(l,true);let del=document.createElement('button');del.textContent='Delete';del.className='danger';del.onclick=()=>{if(confirm('Delete custom level?')){custom.splice(i,1);storeCustom();refresh()}};n.appendChild(del);box.appendChild(n)})}
function levelNode(l,isCustom){let d=document.createElement('div');d.className='item';d.innerHTML=`<div><b>${esc(l.id||'custom')} — ${esc(l.name)}</b><p>${save.beaten[l.id]?'Completed':'Not completed'} • Reward: ${l.reward||2} points</p></div>`;let b=document.createElement('button');b.textContent='Play';b.onclick=()=>startLevel(l);d.appendChild(b);return d}
function renderUpgrades(){let box=$('upgradeList');box.innerHTML='';Object.entries(CONFIG.upgrades).forEach(([id,u])=>{let lv=save.upgrades[id]||0,max=lv>=u.max,d=document.createElement('div');d.className='item';d.innerHTML=`<div><b>${u.name} Lv ${lv}/${u.max}</b><p>Cost: ${max?'MAX':u.cost+' points'}</p></div>`;let b=document.createElement('button');b.textContent='Upgrade';b.disabled=max;b.onclick=()=>{if(save.points<u.cost)return alert('Not enough points.');save.points-=u.cost;save.upgrades[id]++;store();refresh()};d.appendChild(b);box.appendChild(d)})}
function makeCustom(){let name=$('edName').value.trim()||'Custom Level',map=$('edMap').value.split('\n').map(x=>x.trimEnd()).filter(Boolean);let joined=map.join('');if(map.length<3)return alert('Map needs at least 3 rows.'),null;if(!joined.includes('P')||!joined.includes('G'))return alert('Map needs P and G.'),null;return{id:'custom-'+Date.now(),name,reward:2,custom:true,map}}
function saveCustom(){let l=makeCustom();if(!l)return;custom.push(l);storeCustom();refresh();alert('Custom level saved.')}function exportCustom(){let l=makeCustom();if(!l)return;$('shareBox').value=btoa(unescape(encodeURIComponent(JSON.stringify(l))))}function importCustom(){try{let l=JSON.parse(decodeURIComponent(escape(atob($('shareBox').value.trim()))));if(!l.name||!Array.isArray(l.map))throw 0;l.id='custom-'+Date.now();l.custom=true;l.reward=2;custom.push(l);storeCustom();refresh();alert('Imported custom level.')}catch{alert('Import failed.')}}
function startLevel(level){show('game');resize();game={level,stats:stats(),tiles:[],enemies:[],particles:[],camera:{x:0,y:0},idle:CONFIG.idle,complete:false,dead:false,msg:'',msgTimer:0,player:{x:80,y:80,w:28,h:34,vx:0,vy:0,onGround:false,facing:1,dashCd:0,sword:0}};parse(level.map);$('hudName').textContent=level.name;last=performance.now();requestAnimationFrame(loop)}
function parse(map){map.forEach((row,y)=>[...row].forEach((ch,x)=>{let tx=x*CONFIG.tile,ty=y*CONFIG.tile;if(ch==='#')game.tiles.push({x:tx,y:ty,w:40,h:40,type:'solid'});if(ch==='X')game.tiles.push({x:tx,y:ty,w:40,h:40,type:'break'});if(ch==='^')game.tiles.push({x:tx,y:ty+12,w:40,h:28,type:'spike'});if(ch==='P'){game.player.x=tx+6;game.player.y=ty+2}if(ch==='G')game.goal={x:tx,y:ty,w:40,h:40};if(ch==='C')game.enemies.push({x:tx+5,y:ty+4,w:30,h:34,vx:0,vy:0,hp:2,onGround:false})}))}
function loop(now){if(!game)return;let dt=Math.min((now-last)/1000,.033);last=now;update(dt);draw();if($('game').classList.contains('active'))requestAnimationFrame(loop)}
function update(dt){let p=game.player,ix=(keys.ArrowRight||keys.KeyD||mobile.right?1:0)-(keys.ArrowLeft||keys.KeyA||mobile.left?1:0),jump=keys.ArrowUp||keys.KeyW||keys.Space||mobile.jump,dash=keys.ShiftLeft||keys.ShiftRight||keys.KeyE||mobile.dash;if(!game.dead&&!game.complete){if(ix){p.vx+=ix*game.stats.speed*.22;p.facing=ix;game.idle=CONFIG.idle}else if(Math.abs(p.vx)<.1&&p.onGround)game.idle-=dt;else game.idle=Math.max(game.idle-dt*.2,0);if(jump&&p.onGround){p.vy=-game.stats.jump;p.onGround=false;game.idle=CONFIG.idle}if(dash&&p.dashCd<=0){p.vx=p.facing*game.stats.dash;p.dashCd=.8;burst(p.x+p.w/2,p.y+p.h/2,10);game.idle=CONFIG.idle}if(keys.MouseDown&&p.sword<=0)swing();if(game.idle<=0)explode('You stopped moving.')}p.dashCd-=dt;p.sword-=dt;p.vy+=CONFIG.gravity;p.vx*=CONFIG.friction;move(p,p.vx,0);move(p,0,p.vy);enemies(dt);particles(dt);if(!game.dead&&game.goal&&touch(p,game.goal))complete();game.camera.x=clamp(p.x-canvas.width/2,getLevelW()-canvas.width);game.camera.y=clamp(p.y-canvas.height/2,getLevelH()-canvas.height);$('idleHud').textContent=Math.max(0,game.idle).toFixed(1);$('pointsC').textContent=save.points;if(game.msgTimer>0)game.msgTimer-=dt}
function enemies(dt){let p=game.player;game.enemies.forEach(e=>{if(e.dead)return;let dir=Math.sign((p.x+p.w/2)-(e.x+e.w/2))||1;e.vx+=dir*.12;e.vx=clamp(e.vx,-2.5,2.5);e.vy+=CONFIG.gravity;e.vx*=.88;move(e,e.vx,0);move(e,0,e.vy);if(!game.dead&&touch(p,e))explode('A chaser touched you.')})}
function move(o,dx,dy){o.x+=dx;o.y+=dy;o.onGround=false;for(const t of game.tiles){if(!touch(o,t))continue;if(t.type==='spike'&&o===game.player){explode('Spikes are rude.');continue}if(t.type!=='solid'&&t.type!=='break')continue;if(dx>0)o.x=t.x-o.w;if(dx<0)o.x=t.x+t.w;if(dy>0){o.y=t.y-o.h;o.vy=0;o.onGround=true}if(dy<0){o.y=t.y+t.h;o.vy=0}if(dx)o.vx=0}}
function swing(){let p=game.player;p.sword=.22;game.idle=CONFIG.idle;let s={x:p.facing>0?p.x+p.w:p.x-46,y:p.y+4,w:46,h:p.h};game.enemies.forEach(e=>{if(!e.dead&&touch(s,e)){e.hp--;e.vx+=p.facing*6;burst(e.x+15,e.y+15,8);if(e.hp<=0){e.dead=true;burst(e.x+15,e.y+15,18)}}});for(let i=game.tiles.length-1;i>=0;i--){let t=game.tiles[i];if(t.type==='break'&&touch(s,t)){burst(t.x+20,t.y+20,12);game.tiles.splice(i,1)}}}
function explode(reason){if(game.dead||game.complete)return;game.dead=true;game.msg=reason+' Press R to retry.';game.msgTimer=999;burst(game.player.x+14,game.player.y+17,50)}function complete(){game.complete=true;if(!save.beaten[game.level.id]){save.beaten[game.level.id]=true;save.points+=game.level.reward||2;store()}game.msg='Level complete! Press Enter.';game.msgTimer=999;burst(game.goal.x+20,game.goal.y+20,30);refresh()}
function burst(x,y,n){for(let i=0;i<n;i++)game.particles.push({x,y,vx:(Math.random()*2-1)*8,vy:(Math.random()*2-1)*8,life:.5+Math.random()*.6,size:3+Math.random()*6})}function particles(dt){game.particles.forEach(p=>{p.x+=p.vx;p.y+=p.vy;p.vy+=.25;p.life-=dt});game.particles=game.particles.filter(p=>p.life>0)}
function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.save();ctx.translate(-game.camera.x,-game.camera.y);bg();tiles();goal();drawEnemies();player();drawParticles();ctx.restore();if(game.msgTimer>0){ctx.fillStyle='rgba(0,0,0,.76)';ctx.fillRect(0,canvas.height/2-55,canvas.width,110);ctx.strokeStyle='#fff';ctx.strokeRect(20,canvas.height/2-45,canvas.width-40,90);ctx.fillStyle='#fff';ctx.font='bold 30px Arial';ctx.textAlign='center';ctx.fillText(game.msg,canvas.width/2,canvas.height/2+10);ctx.textAlign='left'}}function bg(){let w=getLevelW(),h=getLevelH();ctx.fillStyle='#080808';ctx.fillRect(0,0,w,h);ctx.strokeStyle='#1c1c1c';for(let x=0;x<w;x+=40){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke()}for(let y=0;y<h;y+=40){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}}
function tiles(){game.tiles.forEach(t=>{if(t.type==='solid'){ctx.fillStyle='#ddd';ctx.fillRect(t.x,t.y,t.w,t.h);ctx.strokeStyle='#000';ctx.lineWidth=4;ctx.strokeRect(t.x,t.y,t.w,t.h)}if(t.type==='break'){ctx.fillStyle='#777';ctx.fillRect(t.x,t.y,t.w,t.h);ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.strokeRect(t.x+3,t.y+3,t.w-6,t.h-6)}if(t.type==='spike'){ctx.fillStyle='#fff';ctx.beginPath();ctx.moveTo(t.x,t.y+t.h);ctx.lineTo(t.x+20,t.y);ctx.lineTo(t.x+40,t.y+t.h);ctx.closePath();ctx.fill();ctx.strokeStyle='#000';ctx.stroke()}})}function goal(){let g=game.goal;if(!g)return;ctx.fillStyle='#000';ctx.fillRect(g.x+8,g.y+4,8,g.h);ctx.fillStyle='#fff';ctx.fillRect(g.x+16,g.y+6,24,18);ctx.strokeStyle='#000';ctx.strokeRect(g.x+16,g.y+6,24,18)}function player(){let p=game.player;if(!game.dead){ctx.fillStyle='#fff';ctx.fillRect(p.x,p.y,p.w,p.h);ctx.strokeStyle='#000';ctx.lineWidth=4;ctx.strokeRect(p.x,p.y,p.w,p.h);ctx.fillStyle='#000';ctx.fillRect(p.x+(p.facing>0?18:6),p.y+9,5,5)}if(p.sword>0){ctx.fillStyle='#fff';let sx=p.facing>0?p.x+p.w:p.x-48;ctx.fillRect(sx,p.y+10,48,8);ctx.strokeStyle='#000';ctx.strokeRect(sx,p.y+10,48,8)}}function drawEnemies(){game.enemies.forEach(e=>{if(e.dead)return;ctx.fillStyle='#111';ctx.fillRect(e.x,e.y,e.w,e.h);ctx.strokeStyle='#fff';ctx.lineWidth=3;ctx.strokeRect(e.x,e.y,e.w,e.h);ctx.fillStyle='#fff';ctx.fillRect(e.x+7,e.y+10,5,5);ctx.fillRect(e.x+18,e.y+10,5,5)})}function drawParticles(){game.particles.forEach(p=>{ctx.fillStyle=p.life>.35?'#fff':'#777';ctx.fillRect(p.x,p.y,p.size,p.size)})}
function touch(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y}function clamp(n,min,max){if(max===undefined){max=min;min=0}return Math.max(min,Math.min(max,n))}function getLevelW(){return Math.max(...game.level.map.map(r=>r.length))*40}function getLevelH(){return game.level.map.length*40}function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}function resize(){canvas.width=innerWidth;canvas.height=innerHeight}
addEventListener('resize',resize);addEventListener('keydown',e=>{keys[e.code]=true;if($('game').classList.contains('active')){if(e.code==='KeyR'&&game)startLevel(game.level);if(e.code==='Enter'&&game?.complete)show(game.level.custom?'custom':'levels');if(e.code==='Escape')show('menu')}});addEventListener('keyup',e=>keys[e.code]=false);canvas.addEventListener('mousedown',()=>keys.MouseDown=true);addEventListener('mouseup',()=>keys.MouseDown=false);canvas.addEventListener('touchstart',()=>keys.MouseDown=true,{passive:true});canvas.addEventListener('touchend',()=>keys.MouseDown=false,{passive:true});
function bind(id,prop){let b=$(id);['pointerdown'].forEach(ev=>b.addEventListener(ev,e=>{e.preventDefault();mobile[prop]=true}));['pointerup','pointerleave','pointercancel'].forEach(ev=>b.addEventListener(ev,()=>mobile[prop]=false))}bind('mLeft','left');bind('mRight','right');bind('mJump','jump');bind('mDash','dash');
refresh();show('start');
